name: Publish

on:
  push:
    branches:
      - master
    paths:
      - '.vitepress/**'
      - '*.md'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18
      
      - name: Install dependencies
        run: bun install
      
      - name: Build site
        run: bun run docs:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist
      
      - name: Deploy to pages
        id: deployment
        uses: actions/deploy-pages@v4